---
- name: playbook_dev_tools.yml - Install Development Tools
  hosts: localhost

  tasks:
    - name: Create the aur_builder user
      become: yes
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel

    - name: Allow the aur_builder user to run sudo pacman without a password
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
        create: yes
        mode: 0644
        validate: "visudo -cf %s"

    - name: Install vscode and other dev tools from yay
      kewlfft.aur.aur:
        use: yay
        name:
          - visual-studio-code-bin
          - neovim
          - pyenv-virtualenv
          - google-chrome
          - slack-desktop

    - name: Install dev tools from pacman
      become: yes
      general.community.pacman:
        update_cache: yes
        name:
          - dbeaver
          - wezterm
          - pyenv
          - zellij
          - chezmoi

    - name: Install VS Code extensions
      command: code --install-extension {{ item }}
      with_items:
        - ms-python.python
        - sourcery.sourcery
        - eamodio.gitlens
        - github.vscode-pull-request-github
        - github.remotehub
        - ms-vscode-remote.remote-ssh
        - wayou.vscode-todo-highlight
      register: result
      failed_when: '"already installed" not in result.stdout and result.rc != 0'

  
    - name: Install Python 3.11
      command: pyenv install 3.11.5
      register: pyenv_install
      ignore_errors: true

    - name: Create virtualenv called dev-env with Python 3.11
      command: pyenv virtualenv 3.11.5 dev-env
      register: pyenv_virtualenv_create
      ignore_errors: true

    - name: Check if PYENV_ROOT is defined in .zshrc
      lineinfile:
        path: ~/.zshrc
        line: export PYENV_ROOT="$HOME/.pyenv"
        state: present
        create: yes

    - name: Check if pyenv is in PATH
      lineinfile:
        path: ~/.zshrc
        line: command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
        state: present
        create: yes

    - name: Check if pyenv init is loaded
      lineinfile:
        path: ~/.zshrc
        line: eval "$(pyenv init -)"
        state: present
        create: yes

    - name: Check if pyenv virtualenv init is loaded
      lineinfile:
        path: ~/.zshrc
        line: eval "$(pyenv virtualenv-init -)"
        state: present
        create: yes

